### ISSUE TITLE
Getting "no module: Requests" found error

### ISSUE THREAD

**Issue by mgguinne** [petrepa/BitBar-HASS-fetch#3]
Hi,

Great little plugin, I spent a bit of time on this and made the common error of not having enough slashes in my 'remote_url' params. 

I can get this work locally in the terminal now ( searched the issue about this no module: request and seemed to have fixed it: pip3 install requests), bit in the menu bar (via xbar) it gives the error still. Not sure why? 

Running Big Sir on M1 MacBook air. 

![image](https://user-images.githubusercontent.com/10627164/118750182-45c9d500-b8a2-11eb-8eed-94ebf79a0f92.png)

![image](https://user-images.githubusercontent.com/10627164/118750308-80cc0880-b8a2-11eb-8143-9fbafa7c8537.png)

**Comment by petrepa** [comment]
My quick guess is that you are running different python paths 😄

A possible fix for this might be changing your shebang (the top line) in `HA_fetch.py`
Try changing from 
```
#!/usr/bin/env python3
```
to 
```
#!/usr/local/bin/python
```
and try again.

Lmk how it goes!

**Comment by mgguinne** [comment]
Thanks,

I had to use "#!/usr/local/bin/python3"! Thanks for your help, just needed a pointer in the right direction!
